### ISSUE TITLE
demo.html may not work

### ISSUE THREAD

**Issue by ghost** [tuanchauict/freshsliderjs#3]
Hi Tuan,

We have these lines of code in `demo.html`

``` html
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="freshslider.min.js"></script>
```

If someone clones the repository and try to run `demo.html` from the browser, it wont' work unless they have to manually change `freshslider.min.js` to `freshslider.1.0.min.js`.

**Comment by tuanchauict** [comment]
Done!
Thank you Xuan
