### ISSUE TITLE
Lots of "ReferenceError: event is not defined" appearing on console.

### ISSUE THREAD

**Issue by jomoos** [tuanchauict/freshsliderjs#5]
When I ran the demo provided in the `index.html` file, I encountered lots of `ReferenceError: event is not defined` on Firebug console. After a quick look, the problem seems to be arising from the lines

```
if(event.preventDefault){
    event.preventDefault();
}
```

It happens in two places on `freshslider.1.0.0.js` file:
1. `mousemove` listener function in line [248](https://github.com/tuanchauict/freshsliderjs/blob/master/src/freshslider.1.0.0.js#L248)
2. `mousedown` listener function in line [186](https://github.com/tuanchauict/freshsliderjs/blob/master/src/freshslider.1.0.0.js#L186)

It seems that the event argument is received as `e` and not as `event`. I was able to solve the bug by the replacing `event` with `e` as follows:

```
if(e.preventDefault){
    e.preventDefault();
}
```

**Comment by ghost** [comment]
I just fixed it, @jomoos 

I guess you were using Firefox. The last time I checked, browsers such as Chrome or IE provide a global window.event object that captures the current event inside a callback, while Firefox doesn't. That's why your logged message has never appeared when I use Chrome.
